### ISSUE TITLE
Macos on V1.0 isnt executable

### ISSUE THREAD

**Issue by BenRed06** [ZIBIZ-PROJECT/ZIBIZCORE-WEB#1]
hello. 
im trying to run 1.0 on my old mac, and the file it downloads just opens straight to a text editor. is there a fix to this?

**Comment by ZIBIZ-PROJECT** [comment]
Hey BenRed06, What operating system are you using on your mac?

**Comment by BenRed06** [comment]
macos. native. im saying. the file you uploaded as macos is not an "app". 
how do I run it?

**Comment by ZIBIZ-PROJECT** [comment]
Yes, I just checked, I will contact the other developers to quickly resolve the issue. Sorry for the inconvenience. I will let you know when it's corrected

**Comment by BenRed06** [comment]
ok thank you

**Comment by ZIBIZ-PROJECT** [comment]
No problem!

**Comment by BenRed06** [comment]
when its fixed will you make a new release?

**Comment by ZIBIZ-PROJECT** [comment]
Yes, We are working on an updated version and I will let you know when it's available

**Comment by BenRed06** [comment]
ok awesome
